name: CI

on:
  push:
permissions:
  contents: write

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      # install dependencies --------------------------------------------------

      - name: Install dependencies for Api
        run: yarn

      # start docker compose --------------------------------------------------

      - name: Start Docker Compose service
        run: docker compose up -d

      - name: Wait for Docker Compose service to be ready
        run: sleep 15

      # ping Server -----------------------------------------------------------

      - name: Ping server
        run: 'curl http://localhost:3000'

      # run tests -------------------------------------------------------------

      - name: Run unit tests for api
        run: yarn test

      # stop docker-compose ---------------------------------------------------

      - name: Stop Docker Compose service
        if: always()
        run: docker compose stop
